### ISSUE TITLE
Warning when runs with custom config

### ISSUE THREAD

**Issue by rbudiharso** [electrode-io/electrode-server#11]
I run electrode with NODE_ENV=demo and I get a warning that says `Electrode Server Notice: NODE_ENV (demo) should be empty or one of development,staging,production,test`, is this expected? the `demo.json` itself only contains `{}`.

![screenshot from 2016-10-28 13-53-53](https://cloud.githubusercontent.com/assets/43447/19797718/f386088c-9d16-11e6-8c86-c131adf90775.png)

![screenshot from 2016-10-28 14-02-03](https://cloud.githubusercontent.com/assets/43447/19797744/28c8e15e-9d17-11e6-9e8e-7a887d4e2613.png)

**Comment by ananavati** [comment]
@rbudiharso please refer to the comment here: https://github.com/electrode-io/electrode-server/issues/9#issuecomment-256833203

**Comment by jchip** [comment]
electrode-server internally is aware of the four env listed and it might have some default configs for them.  That message is just to inform you that you've specified one it's not aware of.  Basically FYI.  There's no issues with it.
