### ISSUE TITLE
Use namespaced configuration in confippet

### ISSUE THREAD

**Issue by citelao** [electrode-io/electrode-server#12]
Is it possible to place server configuration into a namespaced section of Confippet? I would like to add my own options to my `default.json` (for authentication keys, etc), and it seems grody to have a section that also gets thrown to `electrode-server`.

Thoughts?

**Comment by jchip** [comment]
essentially all the recognized config files you loaded with confippet are merged into a single JSON object, which is pass around as app config.  extra sections you have are ignored by electrode-server.  There's really no way for electrode-server to influence the config object you passed it.  You can set a property in the object as hidden or something, or make a copy of it and remove your own section before passing.

**Comment by datvong-wm** [comment]
Close due to inactivity
