### ISSUE TITLE
Errors in `createReduxStore` are not logged

### ISSUE THREAD

**Issue by shiki** [electrode-io/electrode-server#16]
Thank you for making Electrode! I have been trying to learn this (and React + Redux) and my experience has been great so far. 

### Problem

I have recently ran into trouble when I tried to get Redux state initialization in the server working. 

1. I generated a new app using the Yeoman generator. 
2. I ran `gulp dev`
3. I figured that I would have to edit `server/views/index-view.js` `createReduxStore` to initialize the state server-side. 
4. I had a JS reference error in my code that took me a while to figure out. Basically, my code was like this:

    ```js
        function createReduxStore(req, match) { // eslint-disable-line
          const initialState = {
            checkBox: {checked: false},
            number: {value: 999}
          };

          i_am_undefined(); // <---- this should throw 

          const store = createStore(rootReducer, initialState);
          return Promise.resolve(store);
        }
    ```

### Current behavior

I was expecting the call to `i_am_undefined()` to throw something like `Unhandled rejection ReferenceError: i_am_undefined is not defined`. Unfortunately, no errors were logged in the console. Opening the app in the browser results in generated HTML but with an empty state:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>electrode-test</title>
    
    <link rel="stylesheet" href="http://127.0.0.1:2992/js/style.css" /><script src="http://127.0.0.1:2992/js/bundle.dev.js"></script>
</head>
<body>
<div class="js-content"></div>
<script>if (window.webappStart) webappStart();</script>
</body>
</html>
```

The browser console shows an error log but does not exactly inform me of my issue:

![electrode-test](https://cloud.githubusercontent.com/assets/198826/20861021/c01efe02-b942-11e6-8a17-38845a8d1c8c.jpg)

### Questions

* How do I configure the app so that the _undefined error_ is logged? I tried but could not find any information on this.
* Is there another way to debug issues like this? I tried debugging with VS code but the debug just skipped that part where there was an exception and continued with the server process.

**Comment by mypark** [comment]
I've been having the same issue as well, and been doing a workaround of console.log the output, `app.routesEngine.render(req).then((result) = console.log(result))` but there's got to be a better way I think

**Comment by donsalari** [comment]
Fixed
