### ISSUE TITLE
How do I configure cookies in electrode server?

### ISSUE THREAD

**Issue by mypark** [electrode-io/electrode-server#17]
I'm trying to get cookie info from the req object. I see how to configure a cookie in hapi.js but how do I pass or configure a cookie in electrode-server? Do I need to pass in a "server" configuration or a "connection" configuration in config/default.json?

Is there already a default cookie configuration in electrode?

**Comment by caoyangs** [comment]
> Electrode server is an imaginatively named, configurable web server using Hapi.js atop Node.js.

So you do it the same way you would do in hapi.js.

**Comment by jchip** [comment]
In more details, the app config you passed to electrode server contains a `server` section.  That is passed to `Hapi.server`.  You can setup Hapi plugins.  You get back the Hapi server instance.  Other than setting up a default listening server at port 3000, electrode server doesn't really have any code that's persistent in your request lifecycle.  Once it completes setting up your Hapi server and your plugins, it's out of the way.  What's left is basically Hapi, and you can handle cookies exactly the way Hapi app should.
