### ISSUE TITLE
On sever start it shows

### ISSUE THREAD

**Issue by Miteshivgroup** [electrode-io/electrode-server#22]
The server does not work on public ipadress of the server but if we run it on private IP server runs properly is this problem on sever or the electrode server?

> Unhandled rejection Error: listen EADDRNOTAVAIL XXX.XXX.XXX.XXX:6180
>     at Object.exports._errnoException (util.js:1018:11)
>     at exports._exceptionWithHostPort (util.js:1041:20)
>     at Server._listen2 (net.js:1245:19)
>     at listen (net.js:1294:10)
>     at net.js:1404:9
>     at _combinedTickCallback (internal/process/next_tick.js:83:11)
>     at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by jchip** [comment]
why don't you check to see if nodejs' default demo works https://nodejs.org/en/about/

It looks like you OS is not allowing the port to be used on the public ip.

**Comment by Miteshivgroup** [comment]
As you said to check default https://nodejs.org/en/about/ the server is not working but if I use express module to get the http request it works and in electrode I am using hapi plugin so what are the ways to switch my server from hapi to express in electrode can you provide a link for the same, or what mechanism express uses so that I can do at my end.
