### ISSUE TITLE
Provide an option to suppress the "Hapi.js server running" startup banner

### ISSUE THREAD

**Issue by bodawei** [electrode-io/electrode-server#23]
When running lots of integration-type tests using the electrode server, we end up with a lot of "noise" in our logs with the "Hapi.js server running" message that gets printed automatically.

It would be nice to have an option that would let us suppress this message in such circumstances.

**Comment by bodawei** [comment]
A gentle nudge here to get feedback on if this seems like an OK idea, and if so what you think of : https://github.com/electrode-io/electrode-server/pull/24

**Comment by louisrowan** [comment]
+1 on this
