### ISSUE TITLE
Are there plans on updating electrode-server to hapi v17?

### ISSUE THREAD

**Issue by thejones** [electrode-io/electrode-server#25]
I am just curious if there are plans on moving to Hapi v17? I apologize for asking here but it appears that the gitter chat is no longer active. Is there a better place to ask? 

Thanks!

**Comment by jchip** [comment]
Hi, yes, we are working on it, still figuring out how to do that.  Sorry for the lack of responses, but it's Black Friday next week and we are all preparing.

**Comment by thejones** [comment]
Awesome! Thank you.

**Comment by SamuelEarl** [comment]
I was wondering if there is a status update or a possible timeline for when Electrode will be updated with hapi v17? Also, do you have plans for updating Electrode with React v16 and React Router v4? If so, do you have a timeline for when that might happen?

Thank you for such an awesome project! I am loving Electrode!
