### ISSUE TITLE
Unable to start hapi server , followed steps from doc as below 

### ISSUE THREAD

**Issue by DeeptiTanniru** [electrode-io/electrode-server#30]
<img width="773" alt="screen shot 2018-01-31 at 12 38 50 pm" src="https://user-images.githubusercontent.com/18408711/35646332-b9e0c1e4-0683-11e8-9b9a-b25fed8ad72c.png">
<img width="1440" alt="screen shot 2018-01-31 at 12 35 57 pm" src="https://user-images.githubusercontent.com/18408711/35646333-b9f60d6a-0683-11e8-9fd7-e02f4d2ad773.png">

**Comment by DeeptiTanniru** [comment]
I checked previous issue on same lines and tried to downgrade node, it did not help. pls provide any suggestions. thanks!

**Comment by jchip** [comment]
Hi, please file issue on Jira for internal project.
