### ISSUE TITLE
Electrode server register plugins timeout

### ISSUE THREAD

**Issue by brandplysreese** [electrode-io/electrode-server#7]
I am getting this error after a fresh install. I followed the instructions from http://www.electrode.io/docs/get_started.html 
and have all requirements.

![screen shot 2016-10-05 at 12 11 41 pm](https://cloud.githubusercontent.com/assets/12085564/19121613/23913d28-8af5-11e6-8e04-1cf2280ee058.png)

**Comment by ezralalonde** [comment]
Try adding:

```
  "electrode": {
    "registerPluginsTimeout": 100000
  },
```
at the top-level of the `config/default.json`. I had the same problem yesterday. (The value `100000` is completely arbitrary).

**Comment by brandplysreese** [comment]
That worked! Thank you.

**Comment by jchip** [comment]
Thanks for reporting the issue.  v1.2.0 should resolve this with a default 25 second timeout.  https://github.com/electrode-io/electrode-server/pull/6
