### ISSUE TITLE
How to add custom deployment config?

### ISSUE THREAD

**Issue by rbudiharso** [electrode-io/electrode-server#9]
I want to have a staging environment, how to add the config for it? when I add staging.json in electrode config folder and run the server with NODE_ENV=staging, its complain it cannot found staging.json

![screenshot from 2016-10-26 10-47-12](https://cloud.githubusercontent.com/assets/43447/19712622/9b1a9f4a-9b69-11e6-9c19-e705dc38c178.png)

**Comment by ananavati** [comment]
@rbudiharso 

thanks for checking out electrode

looking at the logs from the screenshot looks like it is running in PROD mode, could you check and see what is the npm task `prod` which gets run as part of `npm run prod`

**Comment by jchip** [comment]
@rbudiharso thanks for reporting this issue.  fixing.

**Comment by rbudiharso** [comment]
Thank you for acknowledging this, but beside staging, how can I add a custom config? say I want to create a demo environment, what should I do?

**Comment by jchip** [comment]
@rbudiharso add a file `config/demo.json` and run with `NODE_ENV=demo`.  You will need to changes  in PR#10 of course.

**Comment by caoyangs** [comment]
`+ electrode-server@1.2.1`
